### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nicothin** [nicothin/criteria-of-quality-frontend#1]
- [x] Сделать html-представление критериев с чекбоксами и анализом переданного в url-е параметра (передавать id проверяющего и проверяемого + список ошибочных пунктов).
- [x] Добавить ссылку на репозиторий (кол-во звезд)
- [x] Добавить прибитую навигацию
- [x] Для критериев предусмотреть спойлер с подробным описанием (по умолчанию сокрыт)
- [x] Добавить критериям визуальный ID, якорь и визуальную ссылку для якоря
- [x] Убрать нумерацию, дать каждому критерию независящий от номера ID.
- [x] Дописать критерии про код-гайд

--------

- [ ] Прикрутить стайллинт
- [ ] Прикрутить https://www.npmjs.com/package/stylelint-selector-bem-pattern — проверку стилей на БЭМ
